Repository microsoft/fluentui-blazor, pull requests merged in 2024-05, with the labels that each got.

#1993 [MessageBar] Supply a default value for the message intent when using MessageOptions
  src/Core/Components/MessageBar/Message.cs
Labels: bug

#1994 [InputLabel] Add Orientation parameter
  examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
  examples/Demo/Shared/Pages/Toolbar/Examples/ToolbarDefault.razor
  src/Core/Components/Label/FluentInputLabel.razor
  src/Core/Components/Label/FluentInputLabel.razor.cs
  src/Core/Components/Label/FluentInputLabel.razor.css
  src/Core/Enums/Orientation.cs
  tests/Core/Label/FluentInputLabelTests.FluentInputLabel_AdditionalProperties.verified.razor.html
  tests/Core/Label/FluentInputLabelTests.FluentInputLabel_AriaLabel.verified.razor.html
  tests/Core/Label/FluentInputLabelTests.FluentInputLabel_Default.verified.razor.html
  tests/Core/Label/FluentInputLabelTests.FluentInputLabel_Orientation.verified.razor.html
  tests/Core/Label/FluentInputLabelTests.FluentInputLabel_Required.verified.razor.html
  tests/Core/Label/FluentInputLabelTests.razor
  tests/Core/_ToDo/Label/FluentInputLabel.FluentInputLabel_Default.verified.html
  tests/Core/_ToDo/Label/FluentInputLabel.cs
Labels: improvement

#2006 [Tabs] Prevent error 'An item with the same key has already been added.'
  src/Core/Components/Tabs/FluentTabs.razor.cs
Labels: bug

#2007 [Autocomplete] Accessibility: Tab key to go to the Close Button
  examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
  src/Core/Components/Icons/FluentIcon.razor
  src/Core/Components/Icons/FluentIcon.razor.cs
  src/Core/Components/List/FluentAutocomplete.razor
  src/Core/Components/List/FluentAutocomplete.razor.cs
  src/Core/Components/List/FluentAutocomplete.razor.js
  tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_AutofocusAttribute.verified.html
  tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_Empty.verified.html
  tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_Keyboard-ArrowDown.verified.html
  tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_Keyboard-ArrowUp.verified.html
  tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_Keyboard-Backspace.verified.html
  tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_Keyboard-Escape.verified.html
  tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_OnClearWithOverlayHiddenOnEmpty_HasNoOverlay.verified.html
  tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_OnClear_ShowOverlay.verified.html
  tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_Opened.verified.html
  tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_SelectedOptions.verified.html
  tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_SelectedOptions_OnDismissClick.verified.html
  tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_SelectedOptions_Template.verified.html
  tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_Templates.verified.html
  tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_ValueText.verified.html
  tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_ValueText_Clears.verified.html
  tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_Width_Empty.verified.html
Labels: v3, a11y

#2025 [Toast Examples] TimeOut setting in milliseconds
  examples/Demo/Shared/Pages/Toast/Examples/ToastConfirmationToasts.razor
Labels: v3

#2019 [FluentAutocomplete] Accessibility - Add "1 of 3" aria-label when item is selected
  src/Core/Components/List/FluentAutocomplete.razor.cs
  tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_Keyboard-ArrowDown.verified.html
  tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_Keyboard-ArrowUp.verified.html
  tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_Keyboard-Backspace.verified.html
  tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_Keyboard-Escape.verified.html
  tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_Opened.verified.html
  tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_SelectedOptions.verified.html
  tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_SelectedOptions_OnDismissClick.verified.html
  tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_SelectedOptions_Template.verified.html
  tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_Templates.verified.html
Labels: v3, a11y

#2052 [FluentAutocomplete] Add `ImmediateDelay` parameter
  examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
  examples/Demo/Shared/Pages/List/Autocomplete/AutocompletePage.razor
  examples/Demo/Shared/Pages/List/Autocomplete/Examples/AutocompleteManyItems.razor
  src/Core/Components/List/FluentAutocomplete.razor
  src/Core/Components/List/FluentAutocomplete.razor.cs
Labels: improvement

#1945 [TreeView] Add `Items` and `LazyLoadItems` properties
  examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
  examples/Demo/Shared/Pages/TreeView/Examples/TreeViewFlat.razor
  examples/Demo/Shared/Pages/TreeView/Examples/TreeViewWithItems.razor
  examples/Demo/Shared/Pages/TreeView/Examples/TreeViewWithUnlimitedItems.razor
  examples/Demo/Shared/Pages/TreeView/TreeViewPage.razor
  src/Core/Components/TreeView/FluentTreeItem.razor
  src/Core/Components/TreeView/FluentTreeItem.razor.cs
  src/Core/Components/TreeView/FluentTreeView.razor
  src/Core/Components/TreeView/FluentTreeView.razor.cs
  src/Core/Components/TreeView/ITreeViewItem.cs
  src/Core/Components/TreeView/TreeViewItem.cs
  src/Core/Components/TreeView/TreeViewItemExpandedEventArgs.cs
  tests/Core/TreeView/FluentTreeViewItemsTests.FluentTreeViewItems_Default.verified.razor.html
  tests/Core/TreeView/FluentTreeViewItemsTests.FluentTreeViewItems_Disabled.verified.razor.html
  tests/Core/TreeView/FluentTreeViewItemsTests.FluentTreeViewItems_Icons.verified.razor.html
  tests/Core/TreeView/FluentTreeViewItemsTests.FluentTreeViewItems_ItemTemplate.verified.razor.html
  tests/Core/TreeView/FluentTreeViewItemsTests.FluentTreeViewItems_LazyLoading.verified.razor.html
  tests/Core/TreeView/FluentTreeViewItemsTests.FluentTreeViewItems_LazyLoading_Expanded.verified.razor.html
  tests/Core/TreeView/FluentTreeViewItemsTests.FluentTreeViewItems_Selected.verified.razor.html
  tests/Core/TreeView/FluentTreeViewItemsTests.FluentTreeViewItems_SelectedItem.verified.razor.html
  tests/Core/TreeView/FluentTreeViewItemsTests.FluentTreeViewItems_SelectedItem_Change.verified.razor.html
  tests/Core/TreeView/FluentTreeViewItemsTests.razor
  tests/Core/TreeView/FluentTreeViewItemsTests.razor.cs
  tests/Core/TreeView/FluentTreeViewTests.FluentTreeView_CustomContent.verified.razor.html
  tests/Core/TreeView/FluentTreeViewTests.FluentTreeView_Default.verified.razor.html
  tests/Core/TreeView/FluentTreeViewTests.FluentTreeView_FluentTreeItem_Default.verified.razor.html
  tests/Core/TreeView/FluentTreeViewTests.razor
  tests/Core/_ToDo/TreeView/FluentTreeItemTests.cs
  tests/Core/_ToDo/TreeView/FluentTreeViewTests.cs
Labels: feature

#2064 [Templates] Use correct autocomplete values when registering new account
  src/Templates/content/BlazorWeb-CSharp/BlazorWeb-CSharp/Components/Account/Pages/Register.razor
Labels: bug, closed:done

#2038 [FluentIcon] Minor cleanup and clarification
  examples/Demo/Shared/Pages/Icon/IconPage.razor
  src/Core/Components/Icons/FluentIcon.razor.cs
  tests/Core/Icons/FluentIconTests.FluentIcon_Width_EmptyString.verified.razor.html
  tests/Core/Icons/FluentIconTests.razor
Labels: chore, improvement

#2060 [DataGrid] Make SelectColumn work when using ItemsProvider
  examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
  examples/Demo/Shared/Pages/Lab/IssueTester.razor
  src/Core/Components/DataGrid/Columns/SelectColumn.cs
  src/Core/Components/DataGrid/FluentDataGrid.razor
  src/Core/Components/DataGrid/FluentDataGrid.razor.cs
  src/Core/Components/DataGrid/Infrastructure/InternalGridContext.cs
Labels: bug
