Repository microsoft/fluentui-blazor, pull requests merged in 2024-04, with the labels that each got.

#1786 [CounterBadge] Add ShowWhen, Dot, and VerticalPosition.
  examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
  examples/Demo/Shared/Pages/Badge/CounterBadge/CounterBadgePage.razor
  examples/Demo/Shared/Pages/Badge/CounterBadge/Examples/CounterBadgeAppearances.razor
  examples/Demo/Shared/Pages/Badge/CounterBadge/Examples/CounterBadgeBadgeContent.razor
  examples/Demo/Shared/Pages/Badge/CounterBadge/Examples/CounterBadgeConditions.razor
  examples/Demo/Shared/Pages/Badge/CounterBadge/Examples/CounterBadgeDefault.razor
  examples/Demo/Shared/Pages/Badge/CounterBadge/Examples/CounterBadgeDot.razor
  src/Core/Components/CounterBadge/FluentCounterBadge.razor
  src/Core/Components/CounterBadge/FluentCounterBadge.razor.cs
  src/Core/Components/CounterBadge/FluentCounterBadge.razor.css
  tests/Core/CounterBadge/FluentCounterBadgeTests.FluentCounterBadge_AppearanceAttribute-Accent.verified.html
  tests/Core/CounterBadge/FluentCounterBadgeTests.FluentCounterBadge_AppearanceAttribute-Lightweight.verified.html
  tests/Core/CounterBadge/FluentCounterBadgeTests.FluentCounterBadge_AppearanceAttribute-Neutral.verified.html
  tests/Core/CounterBadge/FluentCounterBadgeTests.FluentCounterBadge_AttributesDefaultValues.verified.html
  tests/Core/CounterBadge/FluentCounterBadgeTests.FluentCounterBadge_BackgroundColorAndColorAttribute.verified.html
  tests/Core/CounterBadge/FluentCounterBadgeTests.FluentCounterBadge_BackgroundColorErrorLuminanceDark.verified.html
  tests/Core/CounterBadge/FluentCounterBadgeTests.FluentCounterBadge_BackgroundColorLightweightLuminanceDark.verified.html
  tests/Core/CounterBadge/FluentCounterBadgeTests.FluentCounterBadge_BackgroundColorLightweightLuminanceLight.verified.html
  tests/Core/CounterBadge/FluentCounterBadgeTests.FluentCounterBadge_BackgroundLightWeightAndDarkMode.verified.html
  tests/Core/CounterBadge/FluentCounterBadgeTests.FluentCounterBadge_BackgroundLightWeightAndLightMode.verified.html
  tests/Core/CounterBadge/FluentCounterBadgeTests.FluentCounterBadge_BadgeContent.verified.html
  tests/Core/CounterBadge/FluentCounterBadgeTests.FluentCounterBadge_BadgeContentNoCount.verified.html
  tests/Core/CounterBadge/FluentCounterBadgeTests.FluentCounterBadge_BadgeContentNullWithCount.verified.html
  tests/Core/CounterBadge/FluentCounterBadgeTests.FluentCounterBadge_BadgeContentWithMax.verified.html
  tests/Core/CounterBadge/FluentCounterBadgeTests.FluentCounterBadge_Dot.verified.html
  tests/Core/CounterBadge/FluentCounterBadgeTests.FluentCounterBadge_DotWithCount.verified.html
  tests/Core/CounterBadge/FluentCounterBadgeTests.FluentCounterBadge_NoCount.verified.html
  tests/Core/CounterBadge/FluentCounterBadgeTests.FluentCounterBadge_ShowOverflowAttribute.verified.html
  tests/Core/CounterBadge/FluentCounterBadgeTests.FluentCounterBadge_ShowZeroAttributeCountNot0.verified.html
  tests/Core/CounterBadge/FluentCounterBadgeTests.FluentCounterBadge_ShowZeroAttributeWithCount0.verified.html
  tests/Core/CounterBadge/FluentCounterBadgeTests.FluentCounterBadge_WithAdditionalCssClass.verified.html
  tests/Core/CounterBadge/FluentCounterBadgeTests.FluentCounterBadge_WithAdditionalStyle.verified.html
  tests/Core/CounterBadge/FluentCounterBadgeTests.cs
Labels: feature

#1797 [Templates] CSS fixes and use specific package versions
  src/Templates/content/BlazorWeb-CSharp/BlazorWeb-CSharp.Client/BlazorWeb-CSharp.Client.csproj
  src/Templates/content/BlazorWeb-CSharp/BlazorWeb-CSharp/BlazorWeb-CSharp.csproj
  src/Templates/content/BlazorWeb-CSharp/BlazorWeb-CSharp/Components/Pages/Error.razor
  src/Templates/content/BlazorWeb-CSharp/BlazorWeb-CSharp/wwwroot/app.css
  src/Templates/content/ComponentsWebAssembly-CSharp/wwwroot/css/app.css
Labels: improvement

#1730 [FluentNavMenu] Show child items via `FluentMenu` when collapsed
  examples/Demo/Shared/Pages/NavMenu/Examples/NavMenuCollapsible.razor
  examples/Demo/Shared/Pages/NavMenu/NavMenuPage.razor
  src/Core/Components/Menu/FluentMenu.razor
  src/Core/Components/Menu/FluentMenu.razor.cs
  src/Core/Components/Menu/FluentMenuItem.razor.cs
  src/Core/Components/NavMenu/FluentNavBase.cs
  src/Core/Components/NavMenu/FluentNavGroup.razor
  src/Core/Components/NavMenu/FluentNavGroup.razor.cs
  src/Core/Components/NavMenu/FluentNavLink.razor
  src/Core/Components/NavMenu/FluentNavLink.razor.css
  src/Core/Components/NavMenu/FluentNavMenu.razor.cs
Labels: feature

#1826 [DataGrid] Add remove sort capability
  WHATSNEW.md
  examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
  examples/Demo/Shared/Pages/DataGrid/DataGridPage.razor
  examples/Demo/Shared/Pages/DataGrid/Examples/DataGridTypical.razor
  examples/Demo/Shared/wwwroot/docs/WhatsNew.md
  src/Core/Components/DataGrid/Columns/ColumnBase.razor
  src/Core/Components/DataGrid/Columns/ColumnBase.razor.cs
  src/Core/Components/DataGrid/FluentDataGrid.razor.cs
  src/Core/Components/DataGrid/FluentDataGrid.razor.js
  src/Core/Components/DataGrid/FluentDataGridCell.razor.css
  src/Core/Components/DataGrid/Infrastructure/InternalGridContext.cs
  src/Core/Components/Dialog/Services/DialogService-Dialog.cs
Labels: improvement

#1848 [MenuButton] Add ChildContent so items can be supplied manually
  examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
  examples/Demo/Shared/Pages/MenuButton/Examples/MenuButtonAccentColor.razor
  examples/Demo/Shared/Pages/MenuButton/Examples/MenuButtonAppearance.razor
  examples/Demo/Shared/Pages/MenuButton/Examples/MenuButtonManual.razor
  examples/Demo/Shared/Pages/MenuButton/MenuButtonPage.razor
  src/Core/Components/MenuButton/FluentMenuButton.razor
  src/Core/Components/MenuButton/FluentMenuButton.razor.cs
Labels: improvement

#1871 [AppBar] Apply role requirements
  src/Core/Components/AppBar/FluentAppBar.razor
  src/Core/Components/AppBar/FluentAppBar.razor.css
  src/Core/Components/AppBar/FluentAppBarItem.razor
  src/Core/Components/AppBar/FluentAppBarItem.razor.css
  tests/Core/AppBar/FluentAppBarItemTests.FluentAppBarItem_ChildContent.verified.razor.html
  tests/Core/AppBar/FluentAppBarItemTests.FluentAppBarItem_Default.verified.razor.html
  tests/Core/AppBar/FluentAppBarItemTests.FluentAppBarItem_IconActive.verified.razor.html
  tests/Core/AppBar/FluentAppBarItemTests.FluentAppBarItem_NoText.verified.razor.html
  tests/Core/AppBar/FluentAppBarItemTests.FluentAppBarItem_Tooltip.verified.razor.html
  tests/Core/AppBar/FluentAppBarTests.FluentAppBar_ChildContent.verified.razor.html
  tests/Core/AppBar/FluentAppBarTests.FluentAppBar_NoPopoverSearch.verified.razor.html
  tests/Core/AppBar/FluentAppBarTests.FluentAppBar_Overflow.verified.razor.html
Labels: a11y

#1866 Fix Aspire 3364 by adding IKeyCodeListner and handler
  examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
  examples/Demo/Shared/Pages/DataGrid/DataGridPage.razor
  examples/Demo/Shared/wwwroot/css/site.css
  src/Core/Components/DataGrid/FluentDataGrid.razor.cs
  src/Core/Components/DataGrid/FluentDataGrid.razor.js
Labels: a11y

#1902 [FluentDataGrid] Add column Width parameter
  examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
  examples/Demo/Shared/Pages/DataGrid/DataGridPage.razor
  examples/Demo/Shared/Pages/DataGrid/Examples/DataGridDynamicColumns.razor
  src/Core/Components/DataGrid/Columns/ColumnBase.razor.cs
  src/Core/Components/DataGrid/Columns/PropertyColumn.cs
  src/Core/Components/DataGrid/FluentDataGrid.razor
  src/Core/Components/DataGrid/FluentDataGrid.razor.cs
Labels: improvement

#1776 [Extensions] Add a namespace for extension methods to prevent possible naming clashes
  examples/Demo/AssetExplorer/Components/Pages/IconExplorer.razor
  examples/Demo/Shared/Components/SiteSettingsPanel.razor.cs
  examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
  examples/Demo/Shared/_Imports.razor
  src/Core/Components/CounterBadge/FluentCounterBadge.razor.cs
  src/Core/Components/DateTime/CalendarExtended.cs
  src/Core/Components/DateTime/CalendarTitles.cs
  src/Core/Components/DateTime/FluentCalendar.razor.cs
  src/Core/Components/DateTime/FluentCalendarMonth.cs
  src/Core/Components/DateTime/FluentCalendarYear.cs
  src/Core/Components/DesignSystemProvider/FluentDesignTheme.razor.cs
  src/Core/Components/Grid/FluentGridItem.razor.cs
  src/Core/Components/Icons/FluentIcon.razor.cs
  src/Core/Components/Icons/Icon.cs
  src/Core/Components/Label/FluentLabel.razor.cs
  src/Core/Components/Menu/FluentMenuItem.razor.cs
  src/Core/Components/Radio/FluentRadioGroup.razor.cs
  src/Core/Components/Slider/FluentSlider.razor.cs
  src/Core/Components/TextField/FluentTextField.razor.cs
  src/Core/Extensions/AdditionalAttributesExtensions.cs
  src/Core/Extensions/BooleanExtensions.cs
  src/Core/Extensions/DateTimeExtensions.cs
  src/Core/Extensions/EnumExtensions.cs
  src/Core/Extensions/FluentInputExtensions.cs
  src/Core/Extensions/ServiceCollectionExtensions.cs
  src/Core/Extensions/StringExtensions.cs
  src/Core/_Imports.razor
  tests/Core/DateTime/FluentCalendarTests.razor
  tests/Core/DateTime/ToDateTimeExtensionsTests.cs
  tests/Core/DateTime/ToTimeAgoTests.cs
  tests/Core/Extensions/AdditionalAttributesExtensionsShould.cs
Labels: v3

#1981 Change templates css so body-content height is set and scrollable if…
  src/Templates/content/BlazorWeb-CSharp/BlazorWeb-CSharp/wwwroot/app.css
  src/Templates/content/ComponentsWebAssembly-CSharp/wwwroot/css/app.css
Labels: improvement
