Repository microsoft/fluentui-blazor, pull requests merged in 2024-01, with the labels that each got.

#1368 [DataGrid] - Add Loading and LoadingContent parameters
  examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
  examples/Demo/Shared/Pages/DataGrid/Examples/DataGridRemoteData.razor
  examples/Demo/Shared/Pages/DataGrid/Examples/DataGridTypical.razor
  examples/Demo/Shared/Pages/DataGrid/Examples/DataGridVirtualize.razor
  examples/Demo/Shared/Pages/Lab/IssueTester.razor
  src/Core/Components/DataGrid/FluentDataGrid.razor
  src/Core/Components/DataGrid/FluentDataGrid.razor.cs
  src/Core/Components/DataGrid/FluentDataGrid.razor.css
  src/Core/Components/DataGrid/FluentDataGridRow.razor.cs
Labels: feature

#1334 [FluentSortableList] New component
  examples/Demo/Client/wwwroot/index.html
  examples/Demo/Server/Pages/_Layout.cshtml
  examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
  examples/Demo/Shared/Pages/SortableList/Examples/SortableListCloneBetweenLists.razor
  examples/Demo/Shared/Pages/SortableList/Examples/SortableListDefault.razor
  examples/Demo/Shared/Pages/SortableList/Examples/SortableListDisabledSorting.razor
  examples/Demo/Shared/Pages/SortableList/Examples/SortableListDragHandles.razor
  examples/Demo/Shared/Pages/SortableList/Examples/SortableListFallback.razor
  examples/Demo/Shared/Pages/SortableList/Examples/SortableListFiltering.razor
  examples/Demo/Shared/Pages/SortableList/Examples/SortableListMoveBetweenLists.razor
  examples/Demo/Shared/Pages/SortableList/SortableListPage.razor
  examples/Demo/Shared/Shared/DemoNavMenu.razor
  src/Core/Components/SortableList/FluentSortableList.razor
  src/Core/Components/SortableList/FluentSortableList.razor.cs
  src/Core/Components/SortableList/FluentSortableList.razor.css
  src/Core/Components/SortableList/FluentSortableList.razor.js
  src/Core/Components/SortableList/FluentSortableListEventArgs.cs
  tests/Core/SortableList/FluentSortableListTests.FluentSortableList_Default.verified.razor.html
  tests/Core/SortableList/FluentSortableListTests.razor
Labels: feature

#1375 Some DataGrid Loading/Loading content follow-up work
  examples/Demo/Shared/Pages/DataGrid/Examples/DataGridRemoteData.razor
  examples/Demo/Shared/Pages/DataGrid/Examples/DataGridTypical.razor
  examples/Demo/Shared/Pages/DataGrid/Examples/DataGridVirtualize.razor
  examples/Demo/Shared/Pages/Lab/IssueTester.razor
  src/Core/Components/DataGrid/FluentDataGrid.razor
  src/Core/Components/DataGrid/FluentDataGrid.razor.cs
  src/Core/Components/DataGrid/FluentDataGrid.razor.css
  src/Core/Components/DataGrid/FluentDataGridRow.razor.cs
Labels: improvement

#1385 [Overflow] Add RemoveItem method [v3]
  examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
  examples/Demo/Shared/Pages/Overflow/Examples/OverflowHorizontalExample.razor
  src/Core/Components/Overflow/FluentOverflow.razor.cs
  src/Core/Components/Overflow/FluentOverflowItem.razor.cs
Labels: v3

#1384 [Popover] Add Threshold attributes [v3]
  examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
  examples/Demo/Shared/Pages/Popover/Examples/PopoverDefault.razor
  src/Core/Components/Popover/FluentPopover.razor
  src/Core/Components/Popover/FluentPopover.razor.cs
Labels: v3

#1383 [Accessibility] Autocomplete - Fix up/down arrow and labels for screen reader [v3]
  examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
  examples/Demo/Shared/Pages/KeyCode/Examples/KeyCodeExample.razor
  examples/Demo/Shared/Pages/KeyCode/KeyCodePage.razor
  examples/Demo/Shared/Shared/DemoNavMenu.razor
  src/Core/Components/Accessibility/FluentAccessibilityStatus.razor
  src/Core/Components/Accessibility/FluentAccessibilityStatus.razor.cs
  src/Core/Components/Accessibility/FluentKeyCode.razor
  src/Core/Components/Accessibility/FluentKeyCode.razor.cs
  src/Core/Components/Accessibility/FluentKeyCode.razor.js
  src/Core/Components/Accessibility/FluentKeyCodeEventArgs.cs
  src/Core/Components/List/FluentAutocomplete.razor
  src/Core/Components/List/FluentAutocomplete.razor.cs
  src/Core/Enums/KeyCode.cs
  src/Core/Enums/KeyLocation.cs
  tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_Empty.verified.html
  tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_Keyboard-ArrowDown.verified.html
  tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_Keyboard-ArrowUp.verified.html
  tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_Keyboard-Backspace.verified.html
  tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_Keyboard-Escape.verified.html
  tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_Opened.verified.html
  tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_SelectedOptions.verified.html
  tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_SelectedOptions_OnDismissClick.verified.html
  tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_SelectedOptions_Template.verified.html
  tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_Templates.verified.html
  tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_Width_Empty.verified.html
  tests/Core/List/FluentAutocompleteTests.cs
Labels: v3

#1402 [Checkbox] Fix missing Checkbox "disabled" class [v3]
  src/Core/Components/Checkbox/FluentCheckbox.razor.cs
  tests/Core/Checkbox/FluentCheckboxTests.FluentCheckbox_DisabledParameter.verified.html
Labels: v3

#1408 [KeyCode] Add StopPropagation and TargetId [v3]
  examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
  examples/Demo/Shared/Pages/KeyCode/Examples/KeyCodeExample.razor
  src/Core/Components/Accessibility/FluentKeyCode.razor.cs
  src/Core/Components/Accessibility/FluentKeyCode.razor.js
  src/Core/Components/Accessibility/FluentKeyCodeEventArgs.cs
  tests/Core/List/FluentAutocompleteTests.cs
Labels: v3

#1410 Temporary fix #1391
  src/Templates/content/BlazorWeb-CSharp/BlazorWeb-CSharp/Components/Account/Shared/ExternalLoginPicker.razor
Labels: improvement

#1413 [TooltipService] Add TooltipService.Refresh method [v3]
  examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
  src/Core/Components/Tooltip/Services/ITooltipService.cs
  src/Core/Components/Tooltip/Services/TooltipService.cs
Labels: v3

#1417 [Autocomplete] Fix Autocomplete Enter key in EditForm [v3]
  examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
  examples/Demo/Shared/Pages/BasicFormFluentUIComponents.razor
  src/Core/Components/Accessibility/FluentKeyCode.razor.cs
  src/Core/Components/Accessibility/FluentKeyCode.razor.js
  src/Core/Components/List/FluentAutocomplete.razor
  src/Core/Components/List/FluentAutocomplete.razor.cs
Labels: v3
